# Generated by Django 4.2.6 on 2025-04-29 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adviseravailability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviseravailability',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
