# Generated by Django 4.2.6 on 2025-05-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sr_code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
