# Generated by Django 4.2.6 on 2025-05-02 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_sr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sr_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
